# Main compose setup

##############
# ENV, VOLUMES & NETWORK
x-brif-common:
  &brif-common
  environment:
    &brif-common-env
    BASE_URL: "${BASE_URL}"
    APP_SUBDOMAIN: "${APP_SUBDOMAIN}"
    APP_PORT: "${APP_PORT}"
    SECRET_KEY: "${SECRET_KEY}"
    CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
    DB_NAME: "${DB_NAME}"
    DB_USER: "${DB_USER}"
    DB_PASSWORD: "${DB_PASSWORD}"
    CANTALOUPE_PORT: "${CANTALOUPE_PORT}"
    API_IMAGE_BACKEND: "${API_IMAGE_BACKEND}"
  volumes:
    - ${DATA_DIR}:/opt/data       # change to the project's data location
  links:
    - "cantaloupe:http"

volumes:
  brif_postgres_db_v:
    name: brif_postgres_db_v

networks:
  brif-network:
    name: brif_network
    driver: bridge
    ipam:
      config:
        # range starts at 172.20 to avoid conflicts with the bridge network (172.17)
        - subnet: 172.20.0.0/16


services:
  
##############
# API SERVICES

  api_test:
    <<: *brif-common
    container_name: brif_api_test
    image: brif_api_img
    build:
      context: .
      dockerfile: setup/app/Dockerfile
    command: pytest -vv
    depends_on:
      - cantaloupe
      - db
      - celery
    networks:
      brif-network:
        ipv4_address: 172.20.0.101

  api_prod:
    <<: *brif-common
    container_name: brif_api_prod
    image: brif_api_img
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - api_test
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      brif-network:
        ipv4_address: 172.20.0.102

#####################
# SUPPORTING SERVICES

  cantaloupe:
    container_name: brif_cantaloupe
    image: brif_cantaloupe
    build:
      context: .
      dockerfile: setup/cantaloupe/Dockerfile
    restart: always
    volumes:
      - ${LOGS_DIR}/cantaloupe:/cantaloupe/logs
      # CHANGE WITH CAUTION the next mount as it is tied to cantaloupe/properties
      # via FilesystemSource.BasicLookupStrategy.path_prefix
      - ${CONTENT_DIR}:/mnt/directories
    ports:
      - "${CANTALOUPE_PORT}"
    networks:
      brif-network:
        ipv4_address: 172.20.0.103

  celery:
    container_name: brif_celery
    image: celery_app_img
    build:
      context: .
      dockerfile: setup/celery/Dockerfile
    volumes:
      - ${LOGS_DIR}/celery:/opt/celery_app/logs
      - ${DATA_DIR}:/opt/data       # change to the project's data location
    environment:
      <<: *brif-common-env
    depends_on:
      - rabbitmq
    networks:
      brif-network:
        ipv4_address: 172.20.0.104
  
  rabbitmq:
    container_name: brif_rabbitmq
    image: rabbitmq:3.8-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${LOGS_DIR}/rabbitmq:/var/log/rabbitmq
    networks:
      brif-network:
        ipv4_address: 172.20.0.105

  db:
    container_name: brif_postgres
    build:
      context: .
      dockerfile: setup/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - brif_postgres_db_v:/var/lib/postgresql/data
      - ${LOGS_DIR}/postgres:/var/log/postgresql
    networks:
      brif-network:
        ipv4_address: 172.20.0.106
